export const SHOWS_ACTION_TYPES = {
  SHOWS_LOADING: 'SHOWS_LOADING',
  FETCH_SHOWS_SUCCESS: 'FETCH_SHOWS_SUCCESS',
  FETCH_SEARCH_RESULTS_SUCCESS: 'FETCH_SEARCH_RESULTS_SUCCESS',
  FETCH_SHOWS_ERROR: 'FETCH_SHOWS_ERROR',
  FETCH_MODAL_SHOW_SUCCESS: 'FETCH_MODAL_SHOW_SUCCESS',
  SET_NO_RESULTS: 'SET_NO_RESULTS',
};
